/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthSsoCallbackRouteImport } from './routes/auth/sso.callback'
import { Route as AuthInviteTokenRouteImport } from './routes/auth/invite.$token'
import { Route as AuthenticatedAppUsersRouteImport } from './routes/_authenticated/app/users'
import { Route as AuthenticatedAppUsageRouteImport } from './routes/_authenticated/app/usage'
import { Route as AuthenticatedAppSecretsRouteImport } from './routes/_authenticated/app/secrets'
import { Route as AuthenticatedAppRoutingRouteImport } from './routes/_authenticated/app/routing'
import { Route as AuthenticatedAppQuotasRouteImport } from './routes/_authenticated/app/quotas'
import { Route as AuthenticatedAppProvidersRouteImport } from './routes/_authenticated/app/providers'
import { Route as AuthenticatedAppPoliciesRouteImport } from './routes/_authenticated/app/policies'
import { Route as AuthenticatedAppOrganizationsRouteImport } from './routes/_authenticated/app/organizations'
import { Route as AuthenticatedAppMcpRouteImport } from './routes/_authenticated/app/mcp'
import { Route as AuthenticatedAppKeysRouteImport } from './routes/_authenticated/app/keys'
import { Route as AuthenticatedAppHooksRouteImport } from './routes/_authenticated/app/hooks'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/app/dashboard'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated/app/billing'
import { Route as AuthenticatedAppAccountRouteImport } from './routes/_authenticated/app/account'
import { Route as AuthenticatedAppA2aRouteImport } from './routes/_authenticated/app/a2a'
import { Route as AuthenticatedAppSplatRouteImport } from './routes/_authenticated/app/$'
import { Route as AuthenticatedAppTeamsIndexRouteImport } from './routes/_authenticated/app/teams/index'
import { Route as AuthenticatedAppProjectsIndexRouteImport } from './routes/_authenticated/app/projects/index'
import { Route as AuthenticatedAppTeamsTeamIdRouteImport } from './routes/_authenticated/app/teams/$teamId'
import { Route as AuthenticatedAppSettingsTeamsRouteImport } from './routes/_authenticated/app/settings/teams'
import { Route as AuthenticatedAppSettingsLimitsRouteImport } from './routes/_authenticated/app/settings/limits'
import { Route as AuthenticatedAppSettingsGeneralRouteImport } from './routes/_authenticated/app/settings/general'
import { Route as AuthenticatedAppProjectsProjectIdRouteImport } from './routes/_authenticated/app/projects/$projectId'
import { Route as AuthenticatedAppPlaygroundTtsRouteImport } from './routes/_authenticated/app/playground/tts'
import { Route as AuthenticatedAppPlaygroundSttRouteImport } from './routes/_authenticated/app/playground/stt'
import { Route as AuthenticatedAppPlaygroundMcpRouteImport } from './routes/_authenticated/app/playground/mcp'
import { Route as AuthenticatedAppPlaygroundChatRouteImport } from './routes/_authenticated/app/playground/chat'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/_authenticated/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthSsoCallbackRoute = AuthSsoCallbackRouteImport.update({
  id: '/sso/callback',
  path: '/sso/callback',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthInviteTokenRoute = AuthInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedAppUsersRoute = AuthenticatedAppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppUsageRoute = AuthenticatedAppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppSecretsRoute = AuthenticatedAppSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppRoutingRoute = AuthenticatedAppRoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppQuotasRoute = AuthenticatedAppQuotasRouteImport.update({
  id: '/quotas',
  path: '/quotas',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppProvidersRoute =
  AuthenticatedAppProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppPoliciesRoute =
  AuthenticatedAppPoliciesRouteImport.update({
    id: '/policies',
    path: '/policies',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppOrganizationsRoute =
  AuthenticatedAppOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppMcpRoute = AuthenticatedAppMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppKeysRoute = AuthenticatedAppKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppHooksRoute = AuthenticatedAppHooksRouteImport.update({
  id: '/hooks',
  path: '/hooks',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppAccountRoute = AuthenticatedAppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppA2aRoute = AuthenticatedAppA2aRouteImport.update({
  id: '/a2a',
  path: '/a2a',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppSplatRoute = AuthenticatedAppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppTeamsIndexRoute =
  AuthenticatedAppTeamsIndexRouteImport.update({
    id: '/teams/',
    path: '/teams/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProjectsIndexRoute =
  AuthenticatedAppProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppTeamsTeamIdRoute =
  AuthenticatedAppTeamsTeamIdRouteImport.update({
    id: '/teams/$teamId',
    path: '/teams/$teamId',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSettingsTeamsRoute =
  AuthenticatedAppSettingsTeamsRouteImport.update({
    id: '/settings/teams',
    path: '/settings/teams',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSettingsLimitsRoute =
  AuthenticatedAppSettingsLimitsRouteImport.update({
    id: '/settings/limits',
    path: '/settings/limits',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSettingsGeneralRoute =
  AuthenticatedAppSettingsGeneralRouteImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProjectsProjectIdRoute =
  AuthenticatedAppProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppPlaygroundTtsRoute =
  AuthenticatedAppPlaygroundTtsRouteImport.update({
    id: '/playground/tts',
    path: '/playground/tts',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppPlaygroundSttRoute =
  AuthenticatedAppPlaygroundSttRouteImport.update({
    id: '/playground/stt',
    path: '/playground/stt',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppPlaygroundMcpRoute =
  AuthenticatedAppPlaygroundMcpRouteImport.update({
    id: '/playground/mcp',
    path: '/playground/mcp',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppPlaygroundChatRoute =
  AuthenticatedAppPlaygroundChatRouteImport.update({
    id: '/playground/chat',
    path: '/playground/chat',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/$': typeof AuthenticatedAppSplatRoute
  '/app/a2a': typeof AuthenticatedAppA2aRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/hooks': typeof AuthenticatedAppHooksRoute
  '/app/keys': typeof AuthenticatedAppKeysRoute
  '/app/mcp': typeof AuthenticatedAppMcpRoute
  '/app/organizations': typeof AuthenticatedAppOrganizationsRoute
  '/app/policies': typeof AuthenticatedAppPoliciesRoute
  '/app/providers': typeof AuthenticatedAppProvidersRoute
  '/app/quotas': typeof AuthenticatedAppQuotasRoute
  '/app/routing': typeof AuthenticatedAppRoutingRoute
  '/app/secrets': typeof AuthenticatedAppSecretsRoute
  '/app/usage': typeof AuthenticatedAppUsageRoute
  '/app/users': typeof AuthenticatedAppUsersRoute
  '/auth/invite/$token': typeof AuthInviteTokenRoute
  '/auth/sso/callback': typeof AuthSsoCallbackRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/playground/chat': typeof AuthenticatedAppPlaygroundChatRoute
  '/app/playground/mcp': typeof AuthenticatedAppPlaygroundMcpRoute
  '/app/playground/stt': typeof AuthenticatedAppPlaygroundSttRoute
  '/app/playground/tts': typeof AuthenticatedAppPlaygroundTtsRoute
  '/app/projects/$projectId': typeof AuthenticatedAppProjectsProjectIdRoute
  '/app/settings/general': typeof AuthenticatedAppSettingsGeneralRoute
  '/app/settings/limits': typeof AuthenticatedAppSettingsLimitsRoute
  '/app/settings/teams': typeof AuthenticatedAppSettingsTeamsRoute
  '/app/teams/$teamId': typeof AuthenticatedAppTeamsTeamIdRoute
  '/app/projects/': typeof AuthenticatedAppProjectsIndexRoute
  '/app/teams/': typeof AuthenticatedAppTeamsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/$': typeof AuthenticatedAppSplatRoute
  '/app/a2a': typeof AuthenticatedAppA2aRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/hooks': typeof AuthenticatedAppHooksRoute
  '/app/keys': typeof AuthenticatedAppKeysRoute
  '/app/mcp': typeof AuthenticatedAppMcpRoute
  '/app/organizations': typeof AuthenticatedAppOrganizationsRoute
  '/app/policies': typeof AuthenticatedAppPoliciesRoute
  '/app/providers': typeof AuthenticatedAppProvidersRoute
  '/app/quotas': typeof AuthenticatedAppQuotasRoute
  '/app/routing': typeof AuthenticatedAppRoutingRoute
  '/app/secrets': typeof AuthenticatedAppSecretsRoute
  '/app/usage': typeof AuthenticatedAppUsageRoute
  '/app/users': typeof AuthenticatedAppUsersRoute
  '/auth/invite/$token': typeof AuthInviteTokenRoute
  '/auth/sso/callback': typeof AuthSsoCallbackRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/playground/chat': typeof AuthenticatedAppPlaygroundChatRoute
  '/app/playground/mcp': typeof AuthenticatedAppPlaygroundMcpRoute
  '/app/playground/stt': typeof AuthenticatedAppPlaygroundSttRoute
  '/app/playground/tts': typeof AuthenticatedAppPlaygroundTtsRoute
  '/app/projects/$projectId': typeof AuthenticatedAppProjectsProjectIdRoute
  '/app/settings/general': typeof AuthenticatedAppSettingsGeneralRoute
  '/app/settings/limits': typeof AuthenticatedAppSettingsLimitsRoute
  '/app/settings/teams': typeof AuthenticatedAppSettingsTeamsRoute
  '/app/teams/$teamId': typeof AuthenticatedAppTeamsTeamIdRoute
  '/app/projects': typeof AuthenticatedAppProjectsIndexRoute
  '/app/teams': typeof AuthenticatedAppTeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_authenticated/app/$': typeof AuthenticatedAppSplatRoute
  '/_authenticated/app/a2a': typeof AuthenticatedAppA2aRoute
  '/_authenticated/app/account': typeof AuthenticatedAppAccountRoute
  '/_authenticated/app/billing': typeof AuthenticatedAppBillingRoute
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/hooks': typeof AuthenticatedAppHooksRoute
  '/_authenticated/app/keys': typeof AuthenticatedAppKeysRoute
  '/_authenticated/app/mcp': typeof AuthenticatedAppMcpRoute
  '/_authenticated/app/organizations': typeof AuthenticatedAppOrganizationsRoute
  '/_authenticated/app/policies': typeof AuthenticatedAppPoliciesRoute
  '/_authenticated/app/providers': typeof AuthenticatedAppProvidersRoute
  '/_authenticated/app/quotas': typeof AuthenticatedAppQuotasRoute
  '/_authenticated/app/routing': typeof AuthenticatedAppRoutingRoute
  '/_authenticated/app/secrets': typeof AuthenticatedAppSecretsRoute
  '/_authenticated/app/usage': typeof AuthenticatedAppUsageRoute
  '/_authenticated/app/users': typeof AuthenticatedAppUsersRoute
  '/auth/invite/$token': typeof AuthInviteTokenRoute
  '/auth/sso/callback': typeof AuthSsoCallbackRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/playground/chat': typeof AuthenticatedAppPlaygroundChatRoute
  '/_authenticated/app/playground/mcp': typeof AuthenticatedAppPlaygroundMcpRoute
  '/_authenticated/app/playground/stt': typeof AuthenticatedAppPlaygroundSttRoute
  '/_authenticated/app/playground/tts': typeof AuthenticatedAppPlaygroundTtsRoute
  '/_authenticated/app/projects/$projectId': typeof AuthenticatedAppProjectsProjectIdRoute
  '/_authenticated/app/settings/general': typeof AuthenticatedAppSettingsGeneralRoute
  '/_authenticated/app/settings/limits': typeof AuthenticatedAppSettingsLimitsRoute
  '/_authenticated/app/settings/teams': typeof AuthenticatedAppSettingsTeamsRoute
  '/_authenticated/app/teams/$teamId': typeof AuthenticatedAppTeamsTeamIdRoute
  '/_authenticated/app/projects/': typeof AuthenticatedAppProjectsIndexRoute
  '/_authenticated/app/teams/': typeof AuthenticatedAppTeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/app'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/app/$'
    | '/app/a2a'
    | '/app/account'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/hooks'
    | '/app/keys'
    | '/app/mcp'
    | '/app/organizations'
    | '/app/policies'
    | '/app/providers'
    | '/app/quotas'
    | '/app/routing'
    | '/app/secrets'
    | '/app/usage'
    | '/app/users'
    | '/auth/invite/$token'
    | '/auth/sso/callback'
    | '/app/'
    | '/app/playground/chat'
    | '/app/playground/mcp'
    | '/app/playground/stt'
    | '/app/playground/tts'
    | '/app/projects/$projectId'
    | '/app/settings/general'
    | '/app/settings/limits'
    | '/app/settings/teams'
    | '/app/teams/$teamId'
    | '/app/projects/'
    | '/app/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/app/$'
    | '/app/a2a'
    | '/app/account'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/hooks'
    | '/app/keys'
    | '/app/mcp'
    | '/app/organizations'
    | '/app/policies'
    | '/app/providers'
    | '/app/quotas'
    | '/app/routing'
    | '/app/secrets'
    | '/app/usage'
    | '/app/users'
    | '/auth/invite/$token'
    | '/auth/sso/callback'
    | '/app'
    | '/app/playground/chat'
    | '/app/playground/mcp'
    | '/app/playground/stt'
    | '/app/playground/tts'
    | '/app/projects/$projectId'
    | '/app/settings/general'
    | '/app/settings/limits'
    | '/app/settings/teams'
    | '/app/teams/$teamId'
    | '/app/projects'
    | '/app/teams'
  id:
    | '__root__'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/_authenticated/app'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/_authenticated/app/$'
    | '/_authenticated/app/a2a'
    | '/_authenticated/app/account'
    | '/_authenticated/app/billing'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/hooks'
    | '/_authenticated/app/keys'
    | '/_authenticated/app/mcp'
    | '/_authenticated/app/organizations'
    | '/_authenticated/app/policies'
    | '/_authenticated/app/providers'
    | '/_authenticated/app/quotas'
    | '/_authenticated/app/routing'
    | '/_authenticated/app/secrets'
    | '/_authenticated/app/usage'
    | '/_authenticated/app/users'
    | '/auth/invite/$token'
    | '/auth/sso/callback'
    | '/_authenticated/app/'
    | '/_authenticated/app/playground/chat'
    | '/_authenticated/app/playground/mcp'
    | '/_authenticated/app/playground/stt'
    | '/_authenticated/app/playground/tts'
    | '/_authenticated/app/projects/$projectId'
    | '/_authenticated/app/settings/general'
    | '/_authenticated/app/settings/limits'
    | '/_authenticated/app/settings/teams'
    | '/_authenticated/app/teams/$teamId'
    | '/_authenticated/app/projects/'
    | '/_authenticated/app/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/auth/sso/callback': {
      id: '/auth/sso/callback'
      path: '/sso/callback'
      fullPath: '/auth/sso/callback'
      preLoaderRoute: typeof AuthSsoCallbackRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/invite/$token': {
      id: '/auth/invite/$token'
      path: '/invite/$token'
      fullPath: '/auth/invite/$token'
      preLoaderRoute: typeof AuthInviteTokenRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/app/users': {
      id: '/_authenticated/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AuthenticatedAppUsersRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/usage': {
      id: '/_authenticated/app/usage'
      path: '/usage'
      fullPath: '/app/usage'
      preLoaderRoute: typeof AuthenticatedAppUsageRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/secrets': {
      id: '/_authenticated/app/secrets'
      path: '/secrets'
      fullPath: '/app/secrets'
      preLoaderRoute: typeof AuthenticatedAppSecretsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/routing': {
      id: '/_authenticated/app/routing'
      path: '/routing'
      fullPath: '/app/routing'
      preLoaderRoute: typeof AuthenticatedAppRoutingRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/quotas': {
      id: '/_authenticated/app/quotas'
      path: '/quotas'
      fullPath: '/app/quotas'
      preLoaderRoute: typeof AuthenticatedAppQuotasRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/providers': {
      id: '/_authenticated/app/providers'
      path: '/providers'
      fullPath: '/app/providers'
      preLoaderRoute: typeof AuthenticatedAppProvidersRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/policies': {
      id: '/_authenticated/app/policies'
      path: '/policies'
      fullPath: '/app/policies'
      preLoaderRoute: typeof AuthenticatedAppPoliciesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/organizations': {
      id: '/_authenticated/app/organizations'
      path: '/organizations'
      fullPath: '/app/organizations'
      preLoaderRoute: typeof AuthenticatedAppOrganizationsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/mcp': {
      id: '/_authenticated/app/mcp'
      path: '/mcp'
      fullPath: '/app/mcp'
      preLoaderRoute: typeof AuthenticatedAppMcpRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/keys': {
      id: '/_authenticated/app/keys'
      path: '/keys'
      fullPath: '/app/keys'
      preLoaderRoute: typeof AuthenticatedAppKeysRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/hooks': {
      id: '/_authenticated/app/hooks'
      path: '/hooks'
      fullPath: '/app/hooks'
      preLoaderRoute: typeof AuthenticatedAppHooksRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/billing': {
      id: '/_authenticated/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/account': {
      id: '/_authenticated/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AuthenticatedAppAccountRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/a2a': {
      id: '/_authenticated/app/a2a'
      path: '/a2a'
      fullPath: '/app/a2a'
      preLoaderRoute: typeof AuthenticatedAppA2aRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/$': {
      id: '/_authenticated/app/$'
      path: '/$'
      fullPath: '/app/$'
      preLoaderRoute: typeof AuthenticatedAppSplatRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/teams/': {
      id: '/_authenticated/app/teams/'
      path: '/teams'
      fullPath: '/app/teams/'
      preLoaderRoute: typeof AuthenticatedAppTeamsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/projects/': {
      id: '/_authenticated/app/projects/'
      path: '/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AuthenticatedAppProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/teams/$teamId': {
      id: '/_authenticated/app/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/app/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedAppTeamsTeamIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/settings/teams': {
      id: '/_authenticated/app/settings/teams'
      path: '/settings/teams'
      fullPath: '/app/settings/teams'
      preLoaderRoute: typeof AuthenticatedAppSettingsTeamsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/settings/limits': {
      id: '/_authenticated/app/settings/limits'
      path: '/settings/limits'
      fullPath: '/app/settings/limits'
      preLoaderRoute: typeof AuthenticatedAppSettingsLimitsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/settings/general': {
      id: '/_authenticated/app/settings/general'
      path: '/settings/general'
      fullPath: '/app/settings/general'
      preLoaderRoute: typeof AuthenticatedAppSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/projects/$projectId': {
      id: '/_authenticated/app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedAppProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/playground/tts': {
      id: '/_authenticated/app/playground/tts'
      path: '/playground/tts'
      fullPath: '/app/playground/tts'
      preLoaderRoute: typeof AuthenticatedAppPlaygroundTtsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/playground/stt': {
      id: '/_authenticated/app/playground/stt'
      path: '/playground/stt'
      fullPath: '/app/playground/stt'
      preLoaderRoute: typeof AuthenticatedAppPlaygroundSttRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/playground/mcp': {
      id: '/_authenticated/app/playground/mcp'
      path: '/playground/mcp'
      fullPath: '/app/playground/mcp'
      preLoaderRoute: typeof AuthenticatedAppPlaygroundMcpRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/playground/chat': {
      id: '/_authenticated/app/playground/chat'
      path: '/playground/chat'
      fullPath: '/app/playground/chat'
      preLoaderRoute: typeof AuthenticatedAppPlaygroundChatRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthInviteTokenRoute: typeof AuthInviteTokenRoute
  AuthSsoCallbackRoute: typeof AuthSsoCallbackRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthInviteTokenRoute: AuthInviteTokenRoute,
  AuthSsoCallbackRoute: AuthSsoCallbackRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppSplatRoute: typeof AuthenticatedAppSplatRoute
  AuthenticatedAppA2aRoute: typeof AuthenticatedAppA2aRoute
  AuthenticatedAppAccountRoute: typeof AuthenticatedAppAccountRoute
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppHooksRoute: typeof AuthenticatedAppHooksRoute
  AuthenticatedAppKeysRoute: typeof AuthenticatedAppKeysRoute
  AuthenticatedAppMcpRoute: typeof AuthenticatedAppMcpRoute
  AuthenticatedAppOrganizationsRoute: typeof AuthenticatedAppOrganizationsRoute
  AuthenticatedAppPoliciesRoute: typeof AuthenticatedAppPoliciesRoute
  AuthenticatedAppProvidersRoute: typeof AuthenticatedAppProvidersRoute
  AuthenticatedAppQuotasRoute: typeof AuthenticatedAppQuotasRoute
  AuthenticatedAppRoutingRoute: typeof AuthenticatedAppRoutingRoute
  AuthenticatedAppSecretsRoute: typeof AuthenticatedAppSecretsRoute
  AuthenticatedAppUsageRoute: typeof AuthenticatedAppUsageRoute
  AuthenticatedAppUsersRoute: typeof AuthenticatedAppUsersRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppPlaygroundChatRoute: typeof AuthenticatedAppPlaygroundChatRoute
  AuthenticatedAppPlaygroundMcpRoute: typeof AuthenticatedAppPlaygroundMcpRoute
  AuthenticatedAppPlaygroundSttRoute: typeof AuthenticatedAppPlaygroundSttRoute
  AuthenticatedAppPlaygroundTtsRoute: typeof AuthenticatedAppPlaygroundTtsRoute
  AuthenticatedAppProjectsProjectIdRoute: typeof AuthenticatedAppProjectsProjectIdRoute
  AuthenticatedAppSettingsGeneralRoute: typeof AuthenticatedAppSettingsGeneralRoute
  AuthenticatedAppSettingsLimitsRoute: typeof AuthenticatedAppSettingsLimitsRoute
  AuthenticatedAppSettingsTeamsRoute: typeof AuthenticatedAppSettingsTeamsRoute
  AuthenticatedAppTeamsTeamIdRoute: typeof AuthenticatedAppTeamsTeamIdRoute
  AuthenticatedAppProjectsIndexRoute: typeof AuthenticatedAppProjectsIndexRoute
  AuthenticatedAppTeamsIndexRoute: typeof AuthenticatedAppTeamsIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppSplatRoute: AuthenticatedAppSplatRoute,
  AuthenticatedAppA2aRoute: AuthenticatedAppA2aRoute,
  AuthenticatedAppAccountRoute: AuthenticatedAppAccountRoute,
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppHooksRoute: AuthenticatedAppHooksRoute,
  AuthenticatedAppKeysRoute: AuthenticatedAppKeysRoute,
  AuthenticatedAppMcpRoute: AuthenticatedAppMcpRoute,
  AuthenticatedAppOrganizationsRoute: AuthenticatedAppOrganizationsRoute,
  AuthenticatedAppPoliciesRoute: AuthenticatedAppPoliciesRoute,
  AuthenticatedAppProvidersRoute: AuthenticatedAppProvidersRoute,
  AuthenticatedAppQuotasRoute: AuthenticatedAppQuotasRoute,
  AuthenticatedAppRoutingRoute: AuthenticatedAppRoutingRoute,
  AuthenticatedAppSecretsRoute: AuthenticatedAppSecretsRoute,
  AuthenticatedAppUsageRoute: AuthenticatedAppUsageRoute,
  AuthenticatedAppUsersRoute: AuthenticatedAppUsersRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppPlaygroundChatRoute: AuthenticatedAppPlaygroundChatRoute,
  AuthenticatedAppPlaygroundMcpRoute: AuthenticatedAppPlaygroundMcpRoute,
  AuthenticatedAppPlaygroundSttRoute: AuthenticatedAppPlaygroundSttRoute,
  AuthenticatedAppPlaygroundTtsRoute: AuthenticatedAppPlaygroundTtsRoute,
  AuthenticatedAppProjectsProjectIdRoute:
    AuthenticatedAppProjectsProjectIdRoute,
  AuthenticatedAppSettingsGeneralRoute: AuthenticatedAppSettingsGeneralRoute,
  AuthenticatedAppSettingsLimitsRoute: AuthenticatedAppSettingsLimitsRoute,
  AuthenticatedAppSettingsTeamsRoute: AuthenticatedAppSettingsTeamsRoute,
  AuthenticatedAppTeamsTeamIdRoute: AuthenticatedAppTeamsTeamIdRoute,
  AuthenticatedAppProjectsIndexRoute: AuthenticatedAppProjectsIndexRoute,
  AuthenticatedAppTeamsIndexRoute: AuthenticatedAppTeamsIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
