/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthenticatedAppUsersRouteImport } from './routes/_authenticated/app/users'
import { Route as AuthenticatedAppTeamsRouteImport } from './routes/_authenticated/app/teams'
import { Route as AuthenticatedAppProjectsRouteImport } from './routes/_authenticated/app/projects'
import { Route as AuthenticatedAppPlaygroundRouteImport } from './routes/_authenticated/app/playground'
import { Route as AuthenticatedAppOrganizationsRouteImport } from './routes/_authenticated/app/organizations'
import { Route as AuthenticatedAppKeysRouteImport } from './routes/_authenticated/app/keys'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/app/dashboard'
import { Route as AuthenticatedAppSettingsTeamsRouteImport } from './routes/_authenticated/app/settings/teams'
import { Route as AuthenticatedAppSettingsLimitsRouteImport } from './routes/_authenticated/app/settings/limits'
import { Route as AuthenticatedAppSettingsGeneralRouteImport } from './routes/_authenticated/app/settings/general'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/_authenticated/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppUsersRoute = AuthenticatedAppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppTeamsRoute = AuthenticatedAppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppProjectsRoute =
  AuthenticatedAppProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppPlaygroundRoute =
  AuthenticatedAppPlaygroundRouteImport.update({
    id: '/playground',
    path: '/playground',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppOrganizationsRoute =
  AuthenticatedAppOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppKeysRoute = AuthenticatedAppKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSettingsTeamsRoute =
  AuthenticatedAppSettingsTeamsRouteImport.update({
    id: '/settings/teams',
    path: '/settings/teams',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSettingsLimitsRoute =
  AuthenticatedAppSettingsLimitsRouteImport.update({
    id: '/settings/limits',
    path: '/settings/limits',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSettingsGeneralRoute =
  AuthenticatedAppSettingsGeneralRouteImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/keys': typeof AuthenticatedAppKeysRoute
  '/app/organizations': typeof AuthenticatedAppOrganizationsRoute
  '/app/playground': typeof AuthenticatedAppPlaygroundRoute
  '/app/projects': typeof AuthenticatedAppProjectsRoute
  '/app/teams': typeof AuthenticatedAppTeamsRoute
  '/app/users': typeof AuthenticatedAppUsersRoute
  '/app/settings/general': typeof AuthenticatedAppSettingsGeneralRoute
  '/app/settings/limits': typeof AuthenticatedAppSettingsLimitsRoute
  '/app/settings/teams': typeof AuthenticatedAppSettingsTeamsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/keys': typeof AuthenticatedAppKeysRoute
  '/app/organizations': typeof AuthenticatedAppOrganizationsRoute
  '/app/playground': typeof AuthenticatedAppPlaygroundRoute
  '/app/projects': typeof AuthenticatedAppProjectsRoute
  '/app/teams': typeof AuthenticatedAppTeamsRoute
  '/app/users': typeof AuthenticatedAppUsersRoute
  '/app/settings/general': typeof AuthenticatedAppSettingsGeneralRoute
  '/app/settings/limits': typeof AuthenticatedAppSettingsLimitsRoute
  '/app/settings/teams': typeof AuthenticatedAppSettingsTeamsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/keys': typeof AuthenticatedAppKeysRoute
  '/_authenticated/app/organizations': typeof AuthenticatedAppOrganizationsRoute
  '/_authenticated/app/playground': typeof AuthenticatedAppPlaygroundRoute
  '/_authenticated/app/projects': typeof AuthenticatedAppProjectsRoute
  '/_authenticated/app/teams': typeof AuthenticatedAppTeamsRoute
  '/_authenticated/app/users': typeof AuthenticatedAppUsersRoute
  '/_authenticated/app/settings/general': typeof AuthenticatedAppSettingsGeneralRoute
  '/_authenticated/app/settings/limits': typeof AuthenticatedAppSettingsLimitsRoute
  '/_authenticated/app/settings/teams': typeof AuthenticatedAppSettingsTeamsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/app'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/app/dashboard'
    | '/app/keys'
    | '/app/organizations'
    | '/app/playground'
    | '/app/projects'
    | '/app/teams'
    | '/app/users'
    | '/app/settings/general'
    | '/app/settings/limits'
    | '/app/settings/teams'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/app'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/app/dashboard'
    | '/app/keys'
    | '/app/organizations'
    | '/app/playground'
    | '/app/projects'
    | '/app/teams'
    | '/app/users'
    | '/app/settings/general'
    | '/app/settings/limits'
    | '/app/settings/teams'
  id:
    | '__root__'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/_authenticated/app'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/keys'
    | '/_authenticated/app/organizations'
    | '/_authenticated/app/playground'
    | '/_authenticated/app/projects'
    | '/_authenticated/app/teams'
    | '/_authenticated/app/users'
    | '/_authenticated/app/settings/general'
    | '/_authenticated/app/settings/limits'
    | '/_authenticated/app/settings/teams'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/users': {
      id: '/_authenticated/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AuthenticatedAppUsersRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/teams': {
      id: '/_authenticated/app/teams'
      path: '/teams'
      fullPath: '/app/teams'
      preLoaderRoute: typeof AuthenticatedAppTeamsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/projects': {
      id: '/_authenticated/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AuthenticatedAppProjectsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/playground': {
      id: '/_authenticated/app/playground'
      path: '/playground'
      fullPath: '/app/playground'
      preLoaderRoute: typeof AuthenticatedAppPlaygroundRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/organizations': {
      id: '/_authenticated/app/organizations'
      path: '/organizations'
      fullPath: '/app/organizations'
      preLoaderRoute: typeof AuthenticatedAppOrganizationsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/keys': {
      id: '/_authenticated/app/keys'
      path: '/keys'
      fullPath: '/app/keys'
      preLoaderRoute: typeof AuthenticatedAppKeysRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/settings/teams': {
      id: '/_authenticated/app/settings/teams'
      path: '/settings/teams'
      fullPath: '/app/settings/teams'
      preLoaderRoute: typeof AuthenticatedAppSettingsTeamsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/settings/limits': {
      id: '/_authenticated/app/settings/limits'
      path: '/settings/limits'
      fullPath: '/app/settings/limits'
      preLoaderRoute: typeof AuthenticatedAppSettingsLimitsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/settings/general': {
      id: '/_authenticated/app/settings/general'
      path: '/settings/general'
      fullPath: '/app/settings/general'
      preLoaderRoute: typeof AuthenticatedAppSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppKeysRoute: typeof AuthenticatedAppKeysRoute
  AuthenticatedAppOrganizationsRoute: typeof AuthenticatedAppOrganizationsRoute
  AuthenticatedAppPlaygroundRoute: typeof AuthenticatedAppPlaygroundRoute
  AuthenticatedAppProjectsRoute: typeof AuthenticatedAppProjectsRoute
  AuthenticatedAppTeamsRoute: typeof AuthenticatedAppTeamsRoute
  AuthenticatedAppUsersRoute: typeof AuthenticatedAppUsersRoute
  AuthenticatedAppSettingsGeneralRoute: typeof AuthenticatedAppSettingsGeneralRoute
  AuthenticatedAppSettingsLimitsRoute: typeof AuthenticatedAppSettingsLimitsRoute
  AuthenticatedAppSettingsTeamsRoute: typeof AuthenticatedAppSettingsTeamsRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppKeysRoute: AuthenticatedAppKeysRoute,
  AuthenticatedAppOrganizationsRoute: AuthenticatedAppOrganizationsRoute,
  AuthenticatedAppPlaygroundRoute: AuthenticatedAppPlaygroundRoute,
  AuthenticatedAppProjectsRoute: AuthenticatedAppProjectsRoute,
  AuthenticatedAppTeamsRoute: AuthenticatedAppTeamsRoute,
  AuthenticatedAppUsersRoute: AuthenticatedAppUsersRoute,
  AuthenticatedAppSettingsGeneralRoute: AuthenticatedAppSettingsGeneralRoute,
  AuthenticatedAppSettingsLimitsRoute: AuthenticatedAppSettingsLimitsRoute,
  AuthenticatedAppSettingsTeamsRoute: AuthenticatedAppSettingsTeamsRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
